# Generated by Django 3.1.14 on 2022-10-18 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20221018_2323'),
        ('courses', '0006_course_is_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'コースの情報', 'verbose_name_plural': 'コースの情報'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'コースのリソース', 'verbose_name_plural': 'コースのリソース'},
        ),
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': 'コースのタグ', 'verbose_name_plural': 'コースのタグ'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'コースのレクチャー', 'verbose_name_plural': 'コースのレクチャー'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ビデオ', 'verbose_name_plural': 'ビデオ'},
        ),
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='アップロード時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='バックエンド', max_length=20, verbose_name='コースのカテゴリ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='クリック数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.courseorg', verbose_name='教育機関'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初級'), ('zj', '中級'), ('gj', '高級')], max_length=2, verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='コース特徴'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='コースの詳細'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='お気に入り人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='コースの画像'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='バナーかどうか'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_classics',
            field=models.BooleanField(default=False, verbose_name='クラシクかどうか'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='総時間(分)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='コース名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=300, verbose_name='コースの知らせ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='受講人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='コースのタグ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.teacher', verbose_name='講師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='コースの概要'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='知っておきたいこと'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='アップロード時間'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='ダウンロードURL'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='コース名'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='アップロード時間'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='アップロード時間'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='総時間(分)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='レクチャー名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='アップロード時間'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='総時間(分)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='レクチャー'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ビデオ名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='ビデオURL'),
        ),
    ]
