# Generated by Django 3.1.14 on 2022-10-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20221018_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '通信教育'), ('gr', '個人'), ('gx', '学校')], default='pxjg', max_length=4, verbose_name='機関のカテゴリ'),
        ),
    ]
